# Generated by Django 3.2.3 on 2021-05-17 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('established', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelType', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], default='PETROL', max_length=50)),
                ('engineCapacity', models.IntegerField()),
                ('transmission', models.CharField(max_length=50)),
                ('wheelbase', models.IntegerField()),
                ('groundClearence', models.IntegerField()),
                ('bootSpace', models.IntegerField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_specs', to='CarApi.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_company', to='CarApi.company'),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(related_name='car_feature', to='CarApi.Feature'),
        ),
        migrations.AddField(
            model_name='car',
            name='published_by',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='published_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
